version: '3.8'

services:
  postgres_db:
    container_name: auth-postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_CLIENT=${POSTGRES_CLIENT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - shared-network
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    container_name: auth-redis
    image: redis
    command: redis-server --requirepass ${REDIS_PASS}
    networks:
      - shared-network
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis-data:/data

volumes:
  pg-data:
    external: false
  redis-data:
    driver: local

networks:
  shared-network: {}
